name: Build and Package Windows App

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 26
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and Package Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package

      - name: Upload Installer & Portable Executable
        uses: actions/upload-artifact@v4
        with:
          name: package-json-gui-windows-x64
          path: |
            dist-packaged/*.exe
          if-no-files-found: error
